# Generates Angular TS + HTML + SCSS component files
def generate_code(component_name):
    return {
        "component.ts": f"export class {component_name}Component {{}}",
        "component.html": "<p>Generated by AI</p>",
        "component.scss": ":host { display: block; }"
    }
